[server]
runOnSave = true

[browser]
gatherUsageStats = false

[logger]
level = "error"

[theme]
base = "light"
primaryColor = "#60aa3f"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e6e6e6"
textColor = "#263780"
font = "sans serif"

[client]
showErrorDetails = true

[runner]
fastReruns = true

[watch]
exclude = ["**/torch/**"]


